// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/storage/file/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/storage/file/interfaces.go -destination=./internal/storage/file/mocks.go -package=file
//

// Package file is a generated GoMock package.
package file

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetter is a mock of Getter interface.
type MockGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGetterMockRecorder
	isgomock struct{}
}

// MockGetterMockRecorder is the mock recorder for MockGetter.
type MockGetterMockRecorder struct {
	mock *MockGetter
}

// NewMockGetter creates a new mock instance.
func NewMockGetter(ctrl *gomock.Controller) *MockGetter {
	mock := &MockGetter{ctrl: ctrl}
	mock.recorder = &MockGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetter) EXPECT() *MockGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGetter) Get(key string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGetterMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGetter)(nil).Get), key)
}

// MockSetter is a mock of Setter interface.
type MockSetter struct {
	ctrl     *gomock.Controller
	recorder *MockSetterMockRecorder
	isgomock struct{}
}

// MockSetterMockRecorder is the mock recorder for MockSetter.
type MockSetterMockRecorder struct {
	mock *MockSetter
}

// NewMockSetter creates a new mock instance.
func NewMockSetter(ctrl *gomock.Controller) *MockSetter {
	mock := &MockSetter{ctrl: ctrl}
	mock.recorder = &MockSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetter) EXPECT() *MockSetterMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockSetter) Set(key string, value any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockSetterMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSetter)(nil).Set), key, value)
}

// MockGetAll is a mock of GetAll interface.
type MockGetAll struct {
	ctrl     *gomock.Controller
	recorder *MockGetAllMockRecorder
	isgomock struct{}
}

// MockGetAllMockRecorder is the mock recorder for MockGetAll.
type MockGetAllMockRecorder struct {
	mock *MockGetAll
}

// NewMockGetAll creates a new mock instance.
func NewMockGetAll(ctrl *gomock.Controller) *MockGetAll {
	mock := &MockGetAll{ctrl: ctrl}
	mock.recorder = &MockGetAllMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAll) EXPECT() *MockGetAllMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockGetAll) GetAll() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockGetAllMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockGetAll)(nil).GetAll))
}

// MockMemStorage is a mock of MemStorage interface.
type MockMemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMemStorageMockRecorder
	isgomock struct{}
}

// MockMemStorageMockRecorder is the mock recorder for MockMemStorage.
type MockMemStorageMockRecorder struct {
	mock *MockMemStorage
}

// NewMockMemStorage creates a new mock instance.
func NewMockMemStorage(ctrl *gomock.Controller) *MockMemStorage {
	mock := &MockMemStorage{ctrl: ctrl}
	mock.recorder = &MockMemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemStorage) EXPECT() *MockMemStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMemStorage) Get(key string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMemStorageMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMemStorage)(nil).Get), key)
}

// GetAll mocks base method.
func (m *MockMemStorage) GetAll() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMemStorageMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMemStorage)(nil).GetAll))
}

// Set mocks base method.
func (m *MockMemStorage) Set(key string, value any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockMemStorageMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockMemStorage)(nil).Set), key, value)
}
