# General application settings
app_env: "development"
log_level: "info"

# Server settings
server_address: "localhost:8080"

# Agent settings
poll_interval: 2
report_interval: 10

# Storage settings
store_interval: 300
file_storage_path: "tmp/metrics-db.json"
restore: false

# Database settings
database_dsn: ""

# Key for hashing
key: ""

# Rate limit for requests
rate_limit: 1