# Poll interval in seconds
poll_interval: 2

# Report interval in seconds
report_interval: 10

# Store interval in seconds
store_interval: 300

# Path to file storage
file_storage_path: "tmp/metrics-db.json"

# PostgreSQL DSN
database_dsn: "host=localhost user=postgres password=postgres dbname=metrics port=5432 sslmode=disable"

# Restore metrics from file storage
restore: false

# Server address
server_address: "localhost:8080"

# Log level: debug, info, warn, error, fatal, panic
log_level: "info"

# Application environment: development, production
app_env: "development"