// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/middleware/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/handler/middleware/interfaces.go -destination=./internal/handler/middleware/mocks.go -package=middleware
//

// Package middleware is a generated GoMock package.
package middleware

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMiddlewareLogger is a mock of MiddlewareLogger interface.
type MockMiddlewareLogger struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareLoggerMockRecorder
	isgomock struct{}
}

// MockMiddlewareLoggerMockRecorder is the mock recorder for MockMiddlewareLogger.
type MockMiddlewareLoggerMockRecorder struct {
	mock *MockMiddlewareLogger
}

// NewMockMiddlewareLogger creates a new mock instance.
func NewMockMiddlewareLogger(ctrl *gomock.Controller) *MockMiddlewareLogger {
	mock := &MockMiddlewareLogger{ctrl: ctrl}
	mock.recorder = &MockMiddlewareLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddlewareLogger) EXPECT() *MockMiddlewareLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockMiddlewareLogger) Error(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockMiddlewareLoggerMockRecorder) Error(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockMiddlewareLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockMiddlewareLogger) Info(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockMiddlewareLoggerMockRecorder) Info(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockMiddlewareLogger)(nil).Info), varargs...)
}

// MockDecrypter is a mock of Decrypter interface.
type MockDecrypter struct {
	ctrl     *gomock.Controller
	recorder *MockDecrypterMockRecorder
	isgomock struct{}
}

// MockDecrypterMockRecorder is the mock recorder for MockDecrypter.
type MockDecrypterMockRecorder struct {
	mock *MockDecrypter
}

// NewMockDecrypter creates a new mock instance.
func NewMockDecrypter(ctrl *gomock.Controller) *MockDecrypter {
	mock := &MockDecrypter{ctrl: ctrl}
	mock.recorder = &MockDecrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecrypter) EXPECT() *MockDecrypterMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockDecrypter) Decrypt(data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockDecrypterMockRecorder) Decrypt(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockDecrypter)(nil).Decrypt), data)
}
