// Code generated by MockGen. DO NOT EDIT.
// Source: internal/metrics/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/metrics/interfaces.go -destination=internal/metrics/mocks.go -package=metrics
//

// Package metrics is a generated GoMock package.
package metrics

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsLogger is a mock of MetricsLogger interface.
type MockMetricsLogger struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsLoggerMockRecorder
	isgomock struct{}
}

// MockMetricsLoggerMockRecorder is the mock recorder for MockMetricsLogger.
type MockMetricsLoggerMockRecorder struct {
	mock *MockMetricsLogger
}

// NewMockMetricsLogger creates a new mock instance.
func NewMockMetricsLogger(ctrl *gomock.Controller) *MockMetricsLogger {
	mock := &MockMetricsLogger{ctrl: ctrl}
	mock.recorder = &MockMetricsLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsLogger) EXPECT() *MockMetricsLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockMetricsLogger) Error(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockMetricsLoggerMockRecorder) Error(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockMetricsLogger)(nil).Error), varargs...)
}

// Warn mocks base method.
func (m *MockMetricsLogger) Warn(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockMetricsLoggerMockRecorder) Warn(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockMetricsLogger)(nil).Warn), varargs...)
}
